---
deployment:
  tasks:
    - /bin/mkdir -p /home4/tagforge/public_html/assets/img /home4/tagforge/public_html/assets/css /home4/tagforge/public_html/assets/js /home4/tagforge/public_html/includes /home4/tagforge/public_html/scripts
    - /bin/cp -RF /home4/tagforge/repositories/TagForge.in/assets/. /home4/tagforge/public_html/assets/
    - /bin/cp -RF /home4/tagforge/repositories/TagForge.in/includes/. /home4/tagforge/public_html/includes/
    - /bin/cp -RF /home4/tagforge/repositories/TagForge.in/scripts/. /home4/tagforge/public_html/scripts/
    - /bin/cp -f /home4/tagforge/repositories/TagForge.in/.htaccess /home4/tagforge/public_html/.htaccess
    - /bin/cp -f /home4/tagforge/repositories/TagForge.in/admin.php /home4/tagforge/public_html/admin.php
    - /bin/cp -f /home4/tagforge/repositories/TagForge.in/api.php /home4/tagforge/public_html/api.php
    - /bin/cp -f /home4/tagforge/repositories/TagForge.in/app.php /home4/tagforge/public_html/app.php
    - /bin/cp -f /home4/tagforge/repositories/TagForge.in/index.php /home4/tagforge/public_html/index.php
    - /bin/cp -f /home4/tagforge/repositories/TagForge.in/assets/img/favicon.ico /home4/tagforge/public_html/favicon.ico
    - /bin/cp -f /home4/tagforge/repositories/TagForge.in/assets/img/favicon.png /home4/tagforge/public_html/favicon.png
